### ISSUE TITLE
Byte-order when converting to Guid?

### ISSUE THREAD

**Issue by Bouke** [medo64/Medo.Uuid7#13]
This script:
```c#
using Medo;

var uuid = Uuid7.NewUuid7();
Console.WriteLine($"{uuid}");

var guid = (Guid)uuid;
Console.WriteLine($"{guid}");
```

Outputs something like this:
```
01904bcc-f32e-7209-a817-17d9356c5c98
cc4b9001-2ef3-0972-a817-17d9356c5c98
```

I would expect the outputs to be the same, but some groups are reversed. As I'm using `Guid` throughout my code, as a result I'm storing something that's not UUIDv7.

(.NET 8, ARM)

**Comment by Bouke** [comment]
I think this is related to #6? It seems counter-intuitive to me that the conversion between `Uuid7` and `Guid` would result in bytes being ordered incorrectly.

**Comment by medo64** [comment]
Well, bytes are not actually ordered incorrectly, i.e. raw bytes are exactly the same.

However, problem is that ToString function dealing with Guid output treats some parts of Guid as little endian numbers thus leading to a difference in textual representation.

If I make textual representation the same, I mess up binary. If I keep binary (as I opted to), I mess up textual representation. I'm wrong no matter what I select as default. :)

For keeping it same in textual representation one should use `ToGuidMsSql()` function instead.
```
var guid = Uuid7.NewGuid();
Console.WriteLine($"{uuid}");

var guid = uuid.ToGuidMsSql();
Console.WriteLine($"{guid}");
```

And yes, name of `ToGuidMsSql` function is AWFUL since it doesn't really represent what is happening here, i.e. newer MS SQL also saves stuff in binary order instead of using little-endian shenanigans. I had other ideas for function name:
* `ToNativeGuid`
* `ToGuidLE`
* `ToGuidLogical`
* ...
but I am sorta stuck at the naming. What I know is that next version will obsolete `ToGuidMsSql` and I will try to make it more clear what gets converted into what.

It's unlikely that I will move away from binary compatibility as default, but I am toying with idea of having a static configurable default, e..g something like:
```
Uuid7.DefaultAssumeEndianess = true;

var guid = Uuid7.NewGuid();
Console.WriteLine($"{uuid}");

var guidDef = uuid.ToGuid();
Console.WriteLine($"{guidDef}");

var guidLE = uuid.ToGuid(assumeEndianess: true);
Console.WriteLine($"{guidLE}");

var guidBE = uuid.ToGuid(assumeEndianess: false);
Console.WriteLine($"{guidBE}");
```

In any case, I'll try to dedicate the next weekend to this.

**Comment by Bouke** [comment]
On the point of binary compatibility, `Guid.ToByteArray()` is _not_ the typical binary wire format of a UUID. To get the big endian binary wire format of a Guid in .NET 8 [`Guid.ToByteArray(bool bigEndian)`][1] [was added][2]. See also this note in the [documentation on `Guid.ToByteArray()`][0]:

> Note that the order of bytes in the returned byte array is different from the string representation of a [Guid](https://learn.microsoft.com/en-us/dotnet/api/system.guid?view=net-8.0) value. The order of the beginning four-byte group and the next two two-byte groups is reversed, whereas the order of the last two-byte group and the closing six-byte group is the same.

What this means is that focussing on producing the same output for `ToByteArray()` is misguided as it _does not_ produce the big ending binary wire format.

See also this example where I convert Uuid7 to Guid using the well-defined string representation; which is producing the documented byte arrays:
```c#
using Medo;

var uuid = Uuid7.NewUuid7();
var uuidBytes = uuid.ToByteArray();
Console.WriteLine($"{uuid} Uuid7.ToByteArray():    {string.Join(", ", uuidBytes)}");

var guid = Guid.Parse(uuid.ToString());
var guidBytes = guid.ToByteArray();
Console.WriteLine($"{guid} Guid.ToByteArray():     {string.Join(", ", guidBytes)}");

var guidBigEndian = Guid.Parse(uuid.ToString());
var guidBigEndianBytes = guidBigEndian.ToByteArray(true);
Console.WriteLine($"{guidBigEndian} Guid.ToByteArray(true): {string.Join(", ", guidBigEndianBytes)}");
```
```
01904ea8-0e4b-7170-9276-a88dcad52051 Uuid7.ToByteArray():    1, 144, 78, 168, 14, 75, 113, 112, 146, 118, 168, 141, 202, 213, 32, 81
01904ea8-0e4b-7170-9276-a88dcad52051 Guid.ToByteArray():     168, 78, 144, 1, 75, 14, 112, 113, 146, 118, 168, 141, 202, 213, 32, 81
01904ea8-0e4b-7170-9276-a88dcad52051 Guid.ToByteArray(true): 1, 144, 78, 168, 14, 75, 113, 112, 146, 118, 168, 141, 202, 213, 32, 81
```


[0]: https://learn.microsoft.com/en-us/dotnet/api/system.guid.tobytearray?view=net-8.0#system-guid-tobytearray
[1]: https://learn.microsoft.com/en-us/dotnet/api/system.guid.tobytearray?view=net-8.0#system-guid-tobytearray(system-boolean)
[2]: https://github.com/dotnet/runtime/issues/86798

**Comment by medo64** [comment]
I have added a few overloads to hopefully sort this out. For example, if one wants to match Guid endianness, the following can be used:
```
var uuid = Uuid7.NewUuid7();
var guid = uuid.ToGuid(matchGuidEndianness: true);
```

Please note that implicit conversion operators will still be binary compatible.

As for what the proper endianness is, I would argue that big-endian is the appropriate format of internal bytes and thus of the ToByteArray() output. RFC is quite clear that all bytes are always in big-endian format, independent of the system endianness.

In any case, hopefully these extra overloads will help with converting things back and forth.
