### ISSUE TITLE
Ordering intermittently breaks when generating UUIDs 1 ms apart

### ISSUE THREAD

**Issue by MagnusSandgren** [medo64/Medo.Uuid7#5]
### Expected behaviour
An array of newly generated Uuid7 should be in order. 

### Actual behaviour
Ordering an array of newly generated Uuid7 intermittently shuffles the items. 

### Steps to reproduce
[See Program.cs ](https://gist.github.com/MagnusSandgren/48fb3e0fc402e1e238d1e2f6c51bfff8).
1. Create an array of Uuid7s
2. Clone and order it
3. Compare with original array
4. Observe periodic error. That is - original and ordered cloned array is not in the same order.

### Additional information
* Ran 500_000 iterations with no delay between Uuid7 generation without errors
* Ran 200 iterations with 2 ms delay between Uuid7 generation without errors
* There appears to be a difference in how frequently the errors occur on different machines
* Unable to reproduce with `Thread.Sleep(1)` - maybe only an issue in async code? 
* Ran [Program.cs ](https://gist.github.com/MagnusSandgren/48fb3e0fc402e1e238d1e2f6c51bfff8) 2000 iterations with the following output: [Uuid7 bug rapport.txt](https://github.com/medo64/Medo.Uuid7/files/11946061/Uuid7.bug.rapport.txt).

**Comment by medo64** [comment]
Thank for report! I will try to reproduce and analyze it on my side.

However, the first thing that comes to mind is multi-threading. At this time there is not guarantee that sequence will be maintained for multiple different threads; i.e. each thread has it's own counter.

**Comment by medo64** [comment]
Can you please let me know which version you saw this with?

**Comment by medo64** [comment]
I can definitelly confirm the behavior. This is due to each thread having a different per-thread counter. Each time Task.Delay(1) is called, code continues executing on a different thread.

You don't see that each time, as Task.Delay moves execution into the next millisecond and thus time portion of Uuid7 ensures sequencing. However, Task.Delay can [sometime last less than a millisecond](https://github.com/dotnet/runtime/issues/87112) and thus main counter remains the same while sub-counters are on per-thread basis.

While this is expected (and useful for multi-threaded applications), I can see how that behavior could cause issues when using async code.

My current plan is to make NewUuid7 function have the same guarantee as for a single-threaded application while retaining the current behavior with new Uuid7() for highly multi-threaded scenarios where having a separate counter offers significant benefits.

**Comment by MagnusSandgren** [comment]
Thanks for the quick response and a good explanation of the behaviour 🎉 I would love the option to guarantee uniqueness within the same async context. However, I am guessing the use of (for example) AsyncLocal would negatively impact performance. It could be a nice opt-in feature for those that needs that use-case if it is not the default behaviour 😃

PS: Great work with the implementation of Uuid7. I've not encountered an option for generating truly in-order UUIDs before this package! Keep up the good work! 👍

**Comment by medo64** [comment]
Honestly, I think your expectation was correct. Static method should behave in thread consistent manner.
I have updated code to use non-shared variables when called from NewUuid7 method. Old per-thread behavior will remain with new Uuid7. I also updated comments for each method to reflect the same.

I need to do some regression testing later today and I plan to push updated package later today or tomorrow.

**Comment by medo64** [comment]
Fixed (hopefully :)) package is [out](https://www.nuget.org/packages/Medo.Uuid7/).

**Comment by MagnusSandgren** [comment]
Nice! I've ran 2000 new iterations without any issue. I can see that `Uuid7.NewUuid7()` took a negligible performance hit under normal workflow conditions. I suspect it would be slightly worse under heavy parallel load. But I would argue it’s well worth it. Specially with the option to opt-out for thread safety using `new Uuid7()`. 

Thanks for fixing the issue so quickly! 👍 

![image](https://github.com/medo64/Medo.Uuid7/assets/5285192/599c7105-d493-44b0-aa57-7182e75ff0aa)
